### ISSUE TITLE
Add authentication duration to structured log

### ISSUE THREAD

**Issue by RichardScothern** [facebookincubator/FBOpenSSH#7]
It would be very useful to see how long SSH authentication takes.  We collect auth information in the structured log line, so it makes sense to go there.

Add a key to the structured logging output `auth_duration` with the time it took (in seconds) for authentication to happen.

Add a reasonable test and document the key in the manpage too :)

**Comment by pottar** [comment]
Is there a specific reason this should be in seconds? I think milliseconds would be better in this context since auth generally happens very quickly with non-interactive methods.

**Comment by RichardScothern** [comment]
The authentications that matter are ones that take > 1s.  However, subsecond accuracy is probably desirable here so milliseconds is fine
